---
# tasks file for iac-ansible-theforeman
- name: Instalar Dependencias
  apt: name={{ item }} update_cache=yes state=present
  with_items: 
    - ca-certificates

- name: Instalando dependencia PuppetLabs
  get_url: {{ ansible_distribution_release }}
  url: https://apt.puppetlabs.com/puppet5-release-{{ ansible_distribution_release }}.deb
  dest: /tmp/puppet5-release-{{ ansible_distribution_release }}.deb

- name: Instalando pacote puppet5-release-{{ ansible_distribution_release }}.deb
  apt:
  deb: /tmp/puppet5-release-{{ ansible_distribution_release }}.deb

- apt_repository:
        repo: "deb http://deb.theforeman.org/ {{ ansible_distribution_release }} 1.16"
        state: present

- apt_repository:
        repo: "deb http://deb.theforeman.org/ plugins 1.16"
        state: present

- apt_key: 
  url: "https://deb.theforeman.org/pubkey.gpg"
  state: present

- name: Instalando Docker
  apt: name=foreman-installer update_cache=yes state=latest
...
